version: 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: build
          command: |
            yarn
            yarn build
